local_cache_root = "/home/username/.cache/ragna"

[core]
queue_url = "file://"
document = "ragna.core.LocalDocument"
source_storages = ["ragna.source_storages.Chroma", "ragna.source_storages.RagnaDemoSourceStorage", "ragna.source_storages.LanceDB"]
assistants = ["ragna.assistants.RagnaDemoAssistant", "ragna.assistants.Gpt4", "ragna.assistants.Gpt35Turbo16k"]

[api]
url = "http://127.0.0.1:31476"
origins = ["http://127.0.0.1:31477"]
database_url = "sqlite:///"
authentication = "ragna.core.AuthenticationStub"

[ui]
url = "http://127.0.0.1:31476"
origins = ["http://127.0.0.1:31477"]
